from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8'); start=s.find('<section class="hero">'); end=s.find('</section>',start)
if start<0 or end<0: raise SystemExit('hero section not found')
end+=len('</section>')
hero='''<section class="hero hero-premium"><div class="wrap hero-premium-grid"><div class="hero-premium-copy"><div class="hero-monogram">A <span>♥</span> S</div><div class="eyebrow">Welcome to our love story</div><div class="hero-script">Amit &amp; Shikha</div><div class="hero-serif">Two hearts, one love,<br>and a lifetime together.</div><div class="hero-details"><div class="eyebrow">We are getting married</div><strong>21 November 2026</strong><div class="hero-chips"><span>MJ River Resort</span><span>Rishikesh, Uttarakhand</span><span>#AmitWedsShikha</span></div></div><a class="btn primary" href="#rsvp">RSVP ♥</a></div><div class="hero-premium-frame"><span class="hero-orn hero-o1">❀</span><span class="hero-orn hero-o2">✿</span><span class="hero-corner hero-tl"></span><span class="hero-corner hero-tr"></span><span class="hero-corner hero-bl"></span><span class="hero-corner hero-br"></span><img class="hero-premium-photo" src="images/amit-shikha-hero.webp" alt="Amit and Shikha in a colourful flower garden" fetchpriority="high"></div></div></section>'''
s=s[:start]+hero+s[end:]
css='''<style id="premium-hero-css">.hero-premium{background:radial-gradient(circle at 8% 12%,rgba(249,219,226,.62),transparent 31%),radial-gradient(circle at 92% 10%,rgba(231,224,247,.72),transparent 30%),linear-gradient(180deg,#fffaf6,#fff5f7)}.hero-premium-grid{display:grid;grid-template-columns:.82fr 1.28fr;gap:42px;align-items:center;position:relative;z-index:2}.hero-premium-copy{padding:20px 10px}.hero-monogram{width:84px;height:84px;border:1px solid #c8a15d;border-radius:50%;display:grid;place-items:center;margin-bottom:24px;font:2rem 'Cormorant Garamond',serif;color:#9a6c3d;background:rgba(255,255,255,.58)}.hero-monogram span{font-size:.9rem;color:#b66073}.hero-script{font:clamp(4.3rem,8vw,7.5rem)/.83 'Great Vibes',cursive;color:#a55d70;margin:14px 0 22px}.hero-serif{font:clamp(1.5rem,2.25vw,2.2rem)/1.08 'Cormorant Garamond',serif;color:#604d57}.hero-details{margin-top:24px;padding-top:19px;border-top:1px solid rgba(200,161,93,.5)}.hero-details strong{display:block;font:600 1.5rem 'Cormorant Garamond',serif;margin-top:2px}.hero-chips{display:flex;flex-wrap:wrap;gap:8px;margin-top:15px}.hero-chips span{padding:8px 12px;border-radius:999px;background:#fff;border:1px solid #eee1e3;font-size:.78rem}.hero-premium-frame{position:relative;padding:13px;border-radius:38px;background:#fff;box-shadow:0 25px 80px rgba(92,65,77,.18)}.hero-premium-frame:before{content:"";position:absolute;inset:6px;border:1px solid #c8a15d;border-radius:32px;z-index:2;pointer-events:none}.hero-premium-frame:after{content:"✦   ❀   ✦";position:absolute;left:50%;bottom:7px;transform:translateX(-50%);z-index:3;background:#fffaf6;padding:0 15px;color:#c8a15d;letter-spacing:.22em}.hero-premium-photo{display:block;width:100%;height:min(74vh,720px);object-fit:cover;object-position:center 55%;border-radius:28px}.hero-corner{position:absolute;width:88px;height:88px;border-color:#c8a15d;border-style:solid;z-index:4;pointer-events:none}.hero-tl{left:-3px;top:-3px;border-width:2px 0 0 2px;border-radius:30px 0 0 0}.hero-tr{right:-3px;top:-3px;border-width:2px 2px 0 0;border-radius:0 30px 0 0}.hero-bl{left:-3px;bottom:-3px;border-width:0 0 2px 2px;border-radius:0 0 0 30px}.hero-br{right:-3px;bottom:-3px;border-width:0 2px 2px 0;border-radius:0 0 30px 0}.hero-orn{position:absolute;z-index:4;color:#c8a15d;font-size:2rem}.hero-o1{right:3%;top:2%}.hero-o2{left:3%;bottom:3%}@media(max-width:900px){.hero-premium-grid{grid-template-columns:1fr}.hero-premium-copy{text-align:center}.hero-monogram{margin-inline:auto}.hero-chips{justify-content:center}.hero-premium-frame{margin-top:10px}.hero-premium-photo{height:min(68vh,620px)}} </style>'''
s=s.replace('</head>',css+'</head>',1);p.write_text(s,encoding='utf-8')
